//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogsMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.Design;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class bloguser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bloguser()
        {
            this.blogarticle = new HashSet<blogarticle>();
        }
    
        public int Id { get; set; }
        [DisplayName("登录名")]
        [Required(ErrorMessage ="登录名不能为空")]
        [Remote("Check","blogusers", ErrorMessage = "用户名不存在", HttpMethod = "post")]
        public string LoginName { get; set; }
        [DisplayName("密码")]
        [Required(ErrorMessage ="密码不能为空")]
        public string LoginPwd { get; set; }
        public string CnName { get; set; }
        public string Email { get; set; }
        public bool IsLock { get; set; }
        public bool IsDel { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public string LastLoginIp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blogarticle> blogarticle { get; set; }
    }
}
