//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogsMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bloguser
    {
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string LoginPwd { get; set; }
        public string CnName { get; set; }
        public string Email { get; set; }
        public bool IsLock { get; set; }
        public bool IsDel { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public string LastLoginIp { get; set; }
    }
}
