//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogsMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myblogsEntities : DbContext
    {
        public myblogsEntities()
            : base("name=myblogsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<blogarticle> blogarticle { get; set; }
        public virtual DbSet<bloguser> bloguser { get; set; }
        public virtual DbSet<blogarticlecategory> blogarticlecategory { get; set; }
        public virtual DbSet<blogcommentarticle> blogcommentarticle { get; set; }
        public virtual DbSet<blogcommentphoto> blogcommentphoto { get; set; }
        public virtual DbSet<blogphoto> blogphoto { get; set; }
        public virtual DbSet<blogphotoalblum> blogphotoalblum { get; set; }
        public virtual DbSet<enumeration> enumeration { get; set; }
    }
}
